### ISSUE TITLE
any extra code for releasing for electron?

### ISSUE THREAD

**Issue by pocesar** [pikapkg/builders#10]
or does the bundle-node does the trick?

**Comment by FredKSchott** [comment]
Do you mean to use pika/pack to build an electron app? I actually don't have any experience with that, but if anyone does I'd be super curious how that could work, and game to create an official example and/or builder for it!

**Comment by balupton** [comment]
https://github.com/pikapkg/web/issues/13#issuecomment-471128655

**Comment by FredKSchott** [comment]
Not sure if still actionable, closing now and hoping that https://github.com/pikapkg/web/issues/13#issuecomment-471128655 answers this question
