### ISSUE TITLE
typescript sourcemaps broken

### ISSUE THREAD

**Issue by MarkLyck** [pikapkg/builders#100]
when you run `yarn pika build` in a typescript project with the following plugins the sourcemaps are not generated correctly :(

```
"@pika/pack": {
        "pipeline": [
            [
                "@pika/plugin-ts-standard-pkg"
            ],
            [
                "@pika/plugin-build-web"
            ]
        ]
    },
```

Inside any source map in pkg/dist-src/  it comes out with mappings to sources like this:

`"sources":["../../../src/components/index.ts"]`

In the production package... First of all there's no `src` folder it's called `dist-src` and secondly there's no `.ts` files cause they have been compiled to javascript.

This breaks sourcemaps when trying to load an npm module from @pika/pack in a project.

**Comment by FredKSchott** [comment]
Oh interesting, yea that's no good. I guess having sourcemaps on dist-src/ doesn't make any sense, since its meant to be the ES2020 "source of truth" that others can point their sourcemaps to.

**Comment by FredKSchott** [comment]
Fixed in https://github.com/pikapkg/builders/commit/8e5b1a9b60c0312ad5263357816e64e0ecb412d8 to make sure that we never generateone, although on second glance it looks like we don't generate sourcemaps by default. Can you confirm if your tsconfig.json has `"sourceMap": true`? That could explain why we haven't seen that issue until now

**Comment by MarkLyck** [comment]
Yeah I was trying to debug another problem with @pika/pack and wanted to generate source maps.

The other issue ended up being an incompatibility with @pika/pack and react-admin which for me is a dealbreaker not to use @pika :(. I eventually found out that it's the opinionated way the rollup config of the web builder plugin is using that's causing that.

So basically I'd be forced to either write a custom @pika/pack plugin or just use rollup which seems much easier.

**Comment by FredKSchott** [comment]
Interesting, thanks for sharing the feedback that's really useful to hear. I'd love to know what specific opinionated part of the web builder was causing you trouble.

dist-src/ is supposed to be an as-close-to-source representation of your code, as ES2020. It should be usable as both source map and for any web app bundlers that specifically would like the most modern JS code that you ship. But I do understand wanting the actual `src/` code instead.

**Comment by MarkLyck** [comment]
I'm not entirely sure. Once I narrowed down the problem to the @pika/pack build after spending a full work week investigating the error with no helpful source maps.

it only took me 20 minutes to get a rollup build working in comparison.

We are going to try to write a custom @pika/pack plugin since the Head of Tech REALLY wants to use @pika/pack. So hopefully just changing the rollup config fixes it :/

react-admin isn't doing anything special with imports. So I honestly don't know how or why this build process breaks it. Just that switching out @pika for a basic roll-up config fixed it and was way easier to work with. (for me at least).

I'm sure @pika/pack works fine in 99% of use-cases... But when it doesn't, it's a huge pain not being able to configure anything or easily debug.
