### ISSUE TITLE
@pika/plugin-build-web inlines local imports, changes critical execution path

### ISSUE THREAD

**Issue by lkraav** [pikapkg/builders#102]
Hi. I have a situation with custom elements, where I need to register some DOM (style) modules *before* dependent custom elements are registered and upgraded.

Standard code - works:

```js
import './theme.js';
import '@vaadin/vaadin-tabs';
```

Bundled code - fails:

```js
import '@vaadin/vaadin-tabs';

<inlined `theme.js` here, too late>
```

I'm not sure I can call this a bug? @FredKSchott would you happen to have an idea of what the solution is? How do I make `theme.js` inline itself earlier? :bowing_man:

**Comment by lkraav** [comment]
After re-discovering https://github.com/vaadin/vaadin-themable-mixin/issues/36 and https://github.com/Polymer/tools/issues/802 we think it might be an underlying Rollup issue instead.

**Comment by FredKSchott** [comment]
Yea, this is probably rollup specific. This is a tough one, because I think Rollup is doing the right thing here: ESM gives you no guarantees about execution order of your imports

**Comment by FredKSchott** [comment]
Closing since there's nothing we can do here on our end, but happy to continue discussion
