### ISSUE TITLE
Update rollup dependencies to use scoped registry

### ISSUE THREAD

**Issue by nik-christou** [pikapkg/builders#105]
warning @pika/plugin-bundle-web > rollup-plugin-json@3.1.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
warning @pika/plugin-bundle-web > rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
warning @pika/plugin-bundle-web > rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commons.

**Comment by FredKSchott** [comment]
Fixed in 1de68f1
