### ISSUE TITLE
Bad code cause bin never exit.

### ISSUE THREAD

**Issue by Jack-Works** [pikapkg/builders#108]
https://github.com/pikapkg/builders/blob/ac46b76fd5775fddefd180ca515fe7dc46d03b4f/packages/plugin-simple-bin/src/index.js#L94

In snowpack if there is an error, this code will catch it but never returns.

```js
const run = cli.run || cli.cli || cli.default;
run(process.argv).catch(function (error) {
  console.error(`\n${error.stack || error.message || error}\n`);
    process.exit(1);
});
```

This is better I think

**Comment by FredKSchott** [comment]
Oh wow, that's silly but yea I think you're right. I always wondered why Snowpack hung around after erroring but never exited.

Would you like to make the fix in a PR? Otherwise I'm happy to
