### ISSUE TITLE
Does @pika/plugin-ts-standard-pkg support "excludes" flag 

### ISSUE THREAD

**Issue by tdreyno** [pikapkg/builders#16]
`@pika/plugin-standard-pkg` does, but I can't seem to get it to work with ts.

```
  "@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-ts-standard-pkg",
        {
          "exclude": [
            "sandbox/**/*",
            "testing/**/*",
            "**/__tests__/*",
            "**/stories.ts"
          ]
        }
      ]
    ]
  },
```

Still omits `.js` files for all those paths.

**Comment by FredKSchott** [comment]
Added an "Options" section to the plugin README to describe what options are supported:

https://github.com/pikapkg/builders/blob/master/packages/plugin-ts-standard-pkg/README.md

## Options

This plugin runs `tsc` internally, so it supports all [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) options defined in your project-level config file (like `compilerOptions` & `exclude`).

---

Hopefully that answers your question, if not let me know and I can reopen this issue.

**Comment by tdreyno** [comment]
What I'm looking for is parity with the main `plugin-standard-pkg` where `exclude` globs will avoid placing excluded files in the output `pkg` folder. 

With the above set of options, `plugin-standard-pkg` will generate a `pkg/dist-src` where the files are 1-to-1 with `src`.

With `plugin-ts-standard-pkg`, the `pkg/dist-src` is actually based on the root and `pkg/dist-src` includes another folder `src` (and any other folders present in the root with `.ts` in them).

I think, maybe, that TS needs to have `src` as its root?

I also wonder if TS and whatever is excluding files in `plugin-standard-pkg` have different glob syntaxes. In addition to the root issue, excluding `**/stories.ts` should not result in `stories.js` files occurring in the output `pkg`, but they are.

Let me know and I can make a little repo to reproduce.

**Comment by ithinkihaveacat** [comment]
Suggestion: if the "exclude" is provided, emit a warning pointing to this issue.
