### ISSUE TITLE
Vanity paths

### ISSUE THREAD

**Issue by gilbert** [pikapkg/builders#19]
Pika assumes a `src/` folder and copies everything to `pkg/dist-src/`. However, I would like to provide separate files for certain features in my lib. For example:

```ts
import something from 'my-lib/feature'
```

Specifically with TypeScript, the separation between `dist-src` and `dist-types` dissalows an import from `my-lib/dist-src/feature` as TS cannot find the definition files.

What's the best approach to accomplish this? Any suggestions on plugins?

**Edit**: I say "vanity paths" in the title, but it's not merely for looks. Setting it up this way grants lazier loading of files/features in the package.

**Comment by sandiiarov** [comment]
I have an issue with tree shaking. So, this approach would solve that problem.

**Comment by FredKSchott** [comment]
Lets focus this conversation in this @pika/pack thread: https://github.com/pikapkg/pack/issues/21
