### ISSUE TITLE
Building create-react-app with Typescript

### ISSUE THREAD

**Issue by tomtobac** [pikapkg/builders#20]
I just tried `out-of-box` the pack builder and didn't work as I expected.
Steps:
1. Create a `create-react-app`
2. Add typescript
3. Create random component (`npm run build` works)
4. Add this configuration and install dependencies
```json
  "@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-ts-standard-pkg"
      ],
      [
        "@pika/plugin-build-web"
      ]
    ]
  }
```
5. Run `npx pack build`
```bash
 @pika/pack build v0.3.4
[1/5] Validating source...
[2/5] Preparing pipeline...
      ❇️  pkg/
      » tsconfig.json [compilerOptions.target] should be "es2018", but found "1". You may encounter problems building.
[3/5] Running @pika/plugin-ts-standard-pkg...
Error: Command failed: /home/tcabot/code/my-app/node_modules/.bin/tsc --outDir /home/tcabot/code/my-app/pkg/dist-src/ -d --declarationDir /home/tcabot
/code/my-app/pkg/dist-types/ --declarationMap false --target es2018 --module esnext

tsconfig.json(18,5): error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.

    at makeError (/home/tcabot/code/my-app/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/tcabot/code/my-app/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I thought (as It said in the Readme) to work with all `tsconfig` options, right? :thinking: 
btw, do you guys have any example with `create-react-app` with Typescript (including scss/css)? Thanks!

**Comment by FredKSchott** [comment]
Hey! https://github.com/pikapkg/pack is for building packages (to be published to npm), and will most likely fail when run on an app like `create-react-app`.

**Comment by tomtobac** [comment]
Thanks for the response, I was trying to build a react-component library. I will have to find another way :)

**Comment by FredKSchott** [comment]
That should be supported, but not with CRA unfortunately. it would be good to have an example repo of a React Component in https://github.com/pikapkg/examples

**Comment by tomtobac** [comment]
I could push the example after I make it work, right now I am bit stuck since I copied the default `tsconfig.json` from `create-react-app --typescript` give us
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```
and changed
```json
"isolatedModules": false,
```
since is was rasising this error:
```
tsconfig.json(18,5): error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.
```

After skip this error I removed `pkg/` folder and try again the command and it failed:
```bash

➜  tomeu-button3 npm run build

> tomeu-button3@1.0.0 build /home/tcabot/code/tomeu-button3
> npx pack build --emoji true

@pika/pack build v0.3.4
[1/4] Validating source...
[2/4] Preparing pipeline...
      ❇️  pkg/
      » tsconfig.json [compilerOptions.target] should be "es2018", but found "1". You may encounter proble
ms building.
[3/4] Running @pika/plugin-ts-standard-pkg...
      📝  pkg/dist-src/index.js [esnext]
      📝  pkg/dist-types/index.d.ts [types]
      » Linting with standard-pkg...
[4/4] Finalizing package...
Error: ENOENT: no such file or directory, open '/home/tcabot/code/tomeu-button3/pkg/package.json'
```
I thought every time I run `pack build` it will erase/generate the folder, but looks like it was updating it...
Now I am stuck in this step :sob:

**Comment by griiettner** [comment]
Hi @tomtobac did you have any luck on trying to use create-react-app with @pika?

**Comment by tomtobac** [comment]
Hey @griiettner , no, I am sorry... I couldn't spend more time on it

**Comment by FredKSchott** [comment]
Just to reiterate, publishing a CRA app as a library is out of scope for @pika/pack. CRA does a lot of magic under the hood, and most likely any changes you make to get @pika/pack working will break CRA. 

Feel free to keep discussing. Closing just to signify that publishing a CRA app is not officially supported.
