### ISSUE TITLE
Supporting Flow?

### ISSUE THREAD

**Issue by dangodev** [pikapkg/builders#23]
**Backstory**
I’m on a pikapkg craze at the moment, and I’m playing around with using @pika/web as a webpack replacement in our React projects. Only problem is that `react` doesn’t have an ESM export (of which I’m sure we’re all aware).

“I know!” I thought. “I’ll build React myself with @pika/pack! Problem solved!”

Only @pikapkg doesn’t support Flowtype, and so, sadly, @pika/pack can’t currently pack React.js like it should:
```js
SyntaxError: forwardRef.js: Unexpected token, expected "(" (12:34)

  10 | import warningWithoutStack from './shared/warningWithoutStack';
  11 |
> 12 | export default function forwardRef<Props, ElementType: React$ElementType>(
     |                                   ^
  13 |   render: (props: Props, ref: React$Ref<ElementType>) => React$Node,
  14 | ) {
```

**Problem**
I’d love to help by building a plugin that can handle Flow, but I’m not sure how to go about it.

It seems like each package in the pipeline is in charge of reading the `src` directory on its own, and outputting something in `pkg`. I started trying to create a plugin to remove the flow definitions, but I can’t seem to stop `@pika/plugin-standard-pkg` from reading Flowtype before my Flow plugin can transform it. It seems like the pipeline plugins don’t hand off things to one another so much as they all just read / output their own files independently.

My question is: if I were to open a PR and add a build tool to handle Flow, how would I go about doing that? Would this be a separate plugin, or should we just add [rollup-plugin-flow](https://github.com/leebyron/rollup-plugin-flow) to the standard pkg or something?

**Comment by FredKSchott** [comment]
Hey @dangodev, thanks for your patience. @pika/pack would probably support flow via a top-level `.babelrc` plugin: https://babeljs.io/docs/en/babel-preset-flow

@pika/plugin-standard-pkg uses Babel internally, and will read your project's `.babelrc`.

**Comment by dangodev** [comment]
Sorry; forgot to update the issue. I’ll leave the solution here for others to find.

Your solution does work! If you install the Flow babel plugin and add a `.babelrc`, it’ll process Flow no problem.

My error was actually caused by a potential bug in standard-pkg where if you have `package.json`s inside subfolders, it throws an error. That issue lives here: https://github.com/pikapkg/standard-pkg/issues/3

I’ll close this.
