### ISSUE TITLE
@pika/plugin-copy-assets should update files in package.json

### ISSUE THREAD

**Issue by dangodev** [pikapkg/builders#33]
I have a folder named `ui` that I’m loading like so:

```json
["@pika/plugin-copy-assets", { "files": ["ui/"] } ]
```

However, in `pkg/package.json`, files looks like this:

```json
  "files": [
    "dist-*/",
    "assets/",
    "bin/"
  ],
```

This means that `ui` isn’t being uploaded to npm as intended. Any way to also add `ui` to `files` in the final `package.json` as part of this plugin?

**Comment by FredKSchott** [comment]
Thanks for filing, this was just some simple (or lazy) code on my part. I've added the code to handle this here: https://github.com/pikapkg/builders/commit/36a98a8a21ee9d58d269b79b56e3270dcff829b4

I'll also need to do some cleanup here: https://github.com/pikapkg/pack/blob/6ea20563a6/src/util/normalize-manifest/for-publish.ts#L41-L51

So this won't properly work until the next version of @pika/pack is released as well.

**Comment by FredKSchott** [comment]
Released! (along with @pika/pack)
