### ISSUE TITLE
plugin-simple-bin: Uses dist-node/index if dist-node/index.bundle throws runtime error.

### ISSUE THREAD

**Issue by umidbekkarimov** [pikapkg/builders#35]
[Current implementation](https://github.com/pikapkg/builders/blob/master/packages/plugin-simple-bin/src/index.js#L78-L81) catches all errors and navigates to unbundled module.
We need to add check for `err.code === "MODULE_NOT_FOUND"`.
____
**Update**:  I found that `err.code === "MODULE_NOT_FOUND"` does not work in case `index.bundle.js` has not installed modules. I think that `require.resolve` is the way to go.

**Comment by FredKSchott** [comment]
+1, that makes sense to me. Definitely don't like that it's just swallowing those errors right now.

Thanks for finding and fixing
