### ISSUE TITLE
plugin-ts-standard-pkg should look for tsc in parents folders node_modules

### ISSUE THREAD

**Issue by mulyoved** [pikapkg/builders#42]
Lerna project - Error: "tsc" executable not found. Make sure "typescript" is installed as a project dependency.

Code look for tsc only in current node_modules/.bin should also look in ../node_modules and ../../node_modules (and maybe more)

https://github.com/pikapkg/builders/blob/1a8471e330a399032334ba11b4101281ff5079c6/packages/plugin-ts-standard-pkg/src/index.ts#L46

**Comment by FredKSchott** [comment]
hmm, this issue affects the types plugin as well. Can you share your use case? What is the reason that tsc/typescript isn't a dependency in your package working directory?

**Comment by mulyoved** [comment]
Have a monorepo include few packages and as I don't want to manage multiple dependencies versions for each package I install TS (and all other common dependencies) only on the root of the monorepo folder

**Comment by alexnm** [comment]
Any updates on this? I'm trying pika/pack on a lerna repo and I also noticed I have to install `typescript` as a dependency inside each package.

**Comment by ithinkihaveacat** [comment]
I have the same problem, for a similar (i.e. lerna-related) reason. Is it possible to use the [compiler API](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API) directly, instead of invoking the CLI (a bit weird anyway). Then it would share exactly the same lookup mechanism as node.

**Comment by FredKSchott** [comment]
fixed in #93, thanks everyone!
