### ISSUE TITLE
[@pika/plugin-bundle-web] respect "browser" field in package.json 

### ISSUE THREAD

**Issue by gr2m** [pikapkg/builders#45]
I’m working on bundling https://github.com/octokit/endpoint.js with `@pika/pack` and `@pika/plugin-build-web`/`@pika/plugin-bundle-web`. One dependency is https://github.com/gr2m/universal-user-agent, which defines a custom entry point when building for browsers, using the [`"browser"` field in package.json](https://github.com/gr2m/universal-user-agent/blob/8369bd918179d79c7e556e06704826fdee9a9b7d/package.json#L6)

But instead of using that entry point, the build includes the one intended for Node.js only. 

Is there anything I can do?

I own https://github.com/gr2m/universal-user-agent, so I can also make changes there if it’s helpful

**Comment by FredKSchott** [comment]
Merged in #46!
