### ISSUE TITLE
UMD plugin doesn't bundle non-es imports

### ISSUE THREAD

**Issue by benwiley4000** [pikapkg/builders#48]
It seems like `require('module')` statements are left untouched.

**Comment by FredKSchott** [comment]
@pika/pack assumes all package source is written as ESM, meaning `import` and not `require`. Is that the problem that you're seeing?

If I misunderstood, can you give an example of the source you're writing, the unexpected output you're seeing, and the output you expected to see?

**Comment by benwiley4000** [comment]
Can we remove that assumption? Or have a flag to allow require?

**Comment by benwiley4000** [comment]
If there's a really strong reason to enforce that rule, I can look and see if I can safely change my requires to imports.

**Comment by FredKSchott** [comment]
Yea, that's pretty foundational unfortunately. I'm not even sure if Node.js will be supporting the require function as a global for their ESM code going forward (or iirc their plan may be via some sort of `import {require} from 'nodejs';`)
