### ISSUE TITLE
[@pika/plugin-bundle-web] About minifying...

### ISSUE THREAD

**Issue by alinnert** [pikapkg/builders#56]
I understand the argument that bundling scripts doesn't make that much sense in a http/2 context. But what about minification? It still should matter, in any case, how much data gets transferred over a connection, shouldn't it? You mention minification twice in your blog post "A future without webpack". 1) Together with concatenation it was necessary because of HTTP/1. 2) You can use Terser together with pika/web if you wish. But I can't find any association between Terser/minification and pika/pack.

Wouldn't it make sense to also minify bundles created with `@pika/plugin-bundle-web`? (Of course, the ones with `@pika/plugin-build-*` not so much) So, e.g. I can offer it as a download "my-lib.min.js" from a website or UNPKG.

What is the current way to minify the output created by `@pika/plugin-bundle-web`? Does it make sense to integrate Terser into this plugin? Or can I use Terser directly like I can with pika/web? (I just haven't used pika/web before, so don't know how that works, yet.)

There's a 3rd party plugin `pika-plugin-minify`, but it throws an error at build time. That's why I'm asking for something more official.

**Comment by FredKSchott** [comment]
That's a good point, it would be worth having an option to minify for this bundling plugin, since it's specifically meant for a platform like unpkg. and then maybe even turning that into the default behavior in the next major release.
