### ISSUE TITLE
Autotyping JS?

### ISSUE THREAD

**Issue by selfagency** [pikapkg/builders#57]
It says in the readme here that you can automatically generate types for JS files using `@pika/plugin-build-types`. However, if you're not using TS and you want to use JS files, you have to specify in your `tsconfig.json` to `allowJs`, otherwise TS will say:

```
No inputs were found in config file 'tsconfig.json'.
```

However, if you specify `allowJS`, the error then arises:

```
Option 'allowJs' cannot be specified with option 'declaration'.
```

This is a known [issue with TypeScript](https://github.com/microsoft/TypeScript/issues/7546).

So, the question then is: How is it possible to generate types from my JS? Is there a workaround for this issue, or is it more of a promised future feature that will be delivered upon when TS finally decides to allow the two flags to work with each other?

**Comment by FredKSchott** [comment]
Fixed in 2ba1f99
