### ISSUE TITLE
@pika/plugin-build-types includes @pika/pack both as dep and devDep

### ISSUE THREAD

**Issue by tunnckoCore** [pikapkg/builders#58]
Reviewed the code and seems it isn't used. And don't think we need it as `dependency`, only as `devDependency`

See https://github.com/pikapkg/builders/blob/master/packages/plugin-build-types/package.json#L28

**Comment by FredKSchott** [comment]
Oh wow, great call. That should be a dev dependency, not a regular one 🙈  Fixing now
