### ISSUE TITLE
@pika/plugin-bundle-node: does nothing, because the !isFull

### ISSUE THREAD

**Issue by tunnckoCore** [pikapkg/builders#60]
Any more insight what that `isFull` param is on the `build({ isFull })` is?

When comment it out, everything works and there is final `dist-node/index.bundled.js`

**Comment by FredKSchott** [comment]
Oh wow, yea that's old. I don't think any other plugins still listen to that option. It was meant to be a flag to switch between a quick "dev" build and a larger "full" build for production. You can turn it on by running `npx @pika/pack --publish`, but really it should be removed in favor of some sort of named pipeline solution thats been discussed in other issues.

**Comment by FredKSchott** [comment]
Removed here: https://github.com/pikapkg/builders/commit/df673312d40243e5bb00c6fd72a5696613575363
