### ISSUE TITLE
@pika/pack doesn't link to this repo.

### ISSUE THREAD

**Issue by knpwrs** [pikapkg/builders#7]
The listing for [`@pika/pack`](https://www.npmjs.com/package/@pika/pack) on npm doesn't have a link in the sidebar to easily find this repository. This is actually a common problem with monorepos and I've submitted PRs to other projects to add website entries to `package.json`. It would be nice to see pikapkg handle this.

**Comment by FredKSchott** [comment]
+1, this would be a great first step towards seeing how `@pika/pack publish` could help the user with common config. Actually, in the spirit of the project, could we even read this directly from the current repo / `.git` directory and add it automatically if it's missing?

**Comment by FredKSchott** [comment]
Fixed!
