### ISSUE TITLE
Multiple `entrypoint`s for `@pika/plugin-bundle-web`

### ISSUE THREAD

**Issue by filips123** [pikapkg/builders#71]
Add support for array of `entrypoint`s for `@pika/plugin-bundle-web`. This would be useful if we need to set entrypoints for multiple CDNs like unpkg, jsdelivr... at same time.

For backward compatibility, it should also allow string as one entrypoint. But if there is a list, it should add all of them.

**Comment by FredKSchott** [comment]
+1, that makes sense to me. So the change would be:

```diff
- entrypoint: string,
+ entrypoint: string | string[],
```

Do you want to make the change? Happy to review a PR if so

**Comment by filips123** [comment]
Ok, I will create PR later today.

**Comment by filips123** [comment]
@FredKSchott I created #74.

**Comment by FredKSchott** [comment]
Thanks @filips123!
