### ISSUE TITLE
[plugin-ts-standard-pkg] Unknown System Error on Build

### ISSUE THREAD

**Issue by xlxAciDxlx** [pikapkg/builders#76]
It would be nice if `@pika/plugin-ts-standard-pkg` could output what error/output has occurred when something builds (or at least output the contents of `execa` being executed).

I'm currently getting the following error, despite the same command executing perfectly fine if I manually change to the directory and execute it: (... is my redacted project name)
```txt
Command failed with exit code 1 (Unknown system error -1):
C:\Code\...\packages\api\node_modules\.bin\tsc
--outDir C:\Code\...\packages\api\pkg\dist-src\
-d
--declarationDir C:\Code\...\packages\api\pkg\dist-types\
--project C:\Code\...\packages\api\tsconfig.json
--target es2019
--module esnext
```

### Relevant Information
_package.json:_
```json
"@pika/pack": {
	"pipeline": [
		[
			"@pika/plugin-ts-standard-pkg"
		],
		[
			"@pika/plugin-build-node"
		],
		[
			"@pika/plugin-build-umd"
		],
		[
			"@pika/plugin-build-web"
		]
	]
}
```

_.babelrc:_ (had to add this for support for Decorators and class properties)
```json
{
	"plugins": [
		["@babel/plugin-proposal-decorators", { "legacy": true }],
		["@babel/plugin-proposal-class-properties", { "loose": true }],
		["@babel/plugin-transform-typescript", { "allowNamespaces": true }]
	]
}
```

_tsconfig.json:_ (../../tsconfig.json is my root TS config, just has base compiler options and such)
```json
{
	"extends": "../../tsconfig.json",
	"compilerOptions": {
		"rootDir": "src"
	},
	"files": ["src/index.ts"],
	"include": ["src/**/*.ts", "src/**/*.tsx"]
}
```

If I can provide any more information that may help me track down what's going on with my build failing, please let me know :) Thanks for the awesome work y'all have done with Pika!

**Comment by FredKSchott** [comment]
Yes, +1000. This used to be the case, looks like it regressed recently. Let me look into getting the build error outputting correctly. 

One thing that you can try in the meantime is just running `tsc` in your directory and seeing it's error output. 

One thing I could think of is that `"@pika/plugin-ts-standard-pkg"` uses TypeScript internally. If you'd like your build to go through Babel instead, you should use `"@pika/plugin-standard-pkg" 
and then build your types separately, if you still can: `"@pika/plugin-build-types"`

**Comment by FredKSchott** [comment]
Fixed in https://github.com/pikapkg/pack/commit/e4bfe8775cca987a386bde5d6e465f5c744fc46d
