### ISSUE TITLE
types in generated package.json path points to `dist-types/index.js`

### ISSUE THREAD

**Issue by twop** [pikapkg/builders#8]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/6633216/52528104-2c309080-2c8a-11e9-9a61-2a6256e884de.png">

I think this might be related to this code:
```ts
export function manifest(newManifest) {
  newManifest.source = newManifest.source || 'dist-src/index.js';
  newManifest.types = newManifest.types || 'dist-types/index.js';
  return newManifest;
}
```

**Comment by FredKSchott** [comment]
🤦‍♂️ Can’t believe we didn’t catch that sooner, will push a fix asap. Thanks for finding!

**Comment by FredKSchott** [comment]
Fixed in https://github.com/pikapkg/builders/commit/096f83bf13aa1c2fe8b0640b25c1613b8a983fdd
