### ISSUE TITLE
[plugin-ts-standard-pkg] Does not work with project references

### ISSUE THREAD

**Issue by screendriver** [pikapkg/builders#82]
In almost all of my projects I'm using TypeScript [project references](https://www.typescriptlang.org/docs/handbook/project-references.html). To preserve compatibility with existing build workflows, tsc will not automatically build dependencies unless invoked with the `--build` switch. Unfortunately `@pika/plugin-ts-standard-pkg` just calls `tsc` directly without that flag and it's not possible to add additional CLI arguments to the `options` object.

What would be really great is the ability to do something like this:

```json
"@pika/pack": {
  "pipeline": [
    [
      "@pika/plugin-ts-standard-pkg",
      {
        "args": "--build"
      }
    ]
  ]
}
```

By the way: project references automatically enable incremental builds so the next problem here would be https://github.com/pikapkg/builders/issues/68

**Comment by FredKSchott** [comment]
@screendriver sorry for the delay, but +1 this sounds like a good feature to include as a fallback. Any interest in tackling? If no one grabs it i'll try to get to it soon.
