### ISSUE TITLE
[plugin-ts-standard-pkg] Add support for resolving sub-module definitions

### ISSUE THREAD

**Issue by MaximDevoir** [pikapkg/builders#83]
**The Issue**

TypeScript won't resolve the definitions for non-main files (think files other than index.ts/d.ts). This describes a common scenario in [more detail](https://github.com/microsoft/TypeScript/issues/8305#issuecomment-254017287).

If I try something like:

```TypeScript
import { method } from 'module/submodule'
```

TypeScript will search in "dist-types/index.d.ts" for module declarations of `submodule`, which it won't find. Those definitions were generated to "dist-types/submodule.d.ts". Now the developer doesn't get any type hinting or checking from `submodule`.

**Solutions**

1. Add option to configure output directory for type declaration file. 
1. Developer could export `submodule` from their `index` file so that the submodule will be referenced in the `index.d.ts` file.
1. (Something else?)

**Comment by MaximDevoir** [comment]
The `types` setting in `package.json` also only supports one file.

The definitions would have to be in the same directory as the source file.

```D
<root>
- dist-src
- dist-node
-- index.js
-- index.d.ts
-- submodule.js
-- submodule.d.ts // resolves definition for: import submodule from 'package/submodule'
- dist-types
-- submodule.d.ts // Unresolved for: import submodule from 'package/submodule'
- package.json
```

**Comment by FredKSchott** [comment]
Conceptually, the official project has been focusing more on single-entrypoint packages, so this isn't something that we'll probably get around to tackling. But the pipeline concept is meant to be flexible, and we'd love to point to any community plugins that implement this flow.
