### ISSUE TITLE
tsconfig.json [compilerOptions.target] should be "es2019", but found "5". 

### ISSUE THREAD

**Issue by Jack-Works** [pikapkg/builders#88]
"5" is ts.ScriptTarget.ES2018, pikapkg should transform back the enum value to "ES2018"

**Comment by aeisenberg** [comment]
Bump...I'm getting the same error, but with different versions:

`tsconfig.json [compilerOptions.target] should be "es2019", but found "8". You may encounter problems building.`

**Comment by FredKSchott** [comment]
+1, this should be an easy one if anyone wants to help tackle

**Comment by yumauri** [comment]
Made PR #95 for that
```
» tsconfig.json [compilerOptions.target] should be "es2019", but found "es2015". You may encounter problems building.
» tsconfig.json [compilerOptions.module] should be "esnext", but found "commonjs". You may encounter problems building.
```

**Comment by FredKSchott** [comment]
![you're awesome](https://media.giphy.com/media/bv4mJuzEcOmIg/giphy.gif)

Thanks @yumauri!  Just merged, will do a release later today to get this out
