### ISSUE TITLE
GitHub repository template to create a plugin

### ISSUE THREAD

**Issue by kevinpollet** [pikapkg/builders#92]
Hi,

First of all, thanks for your work!

Currently, as said in #43, there is no documentation to explain how to write a @pika/pack plugin. Following the work I've done to write a plugin, I've created a GitHub repository template to create a @pika/pack plugin project in one click:  https://github.com/kevinpollet/pika-pack-plugin-template#readme.

There are some things to improve like: Documentation, Project set-up by providing a script or an npm [initializer](https://docs.npmjs.com/cli/init#description), ...

WDYT?

**Comment by FredKSchott** [comment]
This is great! Can I link to it in the README / tweet something out?

**Comment by kevinpollet** [comment]
Thanks, of course!

**Comment by FredKSchott** [comment]
Done, 
Here: https://github.com/pikapkg/builders/commit/5fca498d6fcf48ee1994289f67160b6ec5f3923e
& here: https://twitter.com/pikapkg/status/1186391424758996992

Thanks again Kevin!
